encoder_hub_path: hf_hub:mwalmsley/baseline-encoder-regression-convnext_nano
architecture_name: convnext_nano
from_scratch: False
channels: 3  # used for augs
input_size: 224  # used for augs
normalize: False

batch_size: 32
patience: 6
stochastic_depth: 0.0



# deep finetune with decay
learning_rate: 0.00001  # 1e-5
layer_decay: 0.25
weight_decay: 0.1
dropout_prob: 0.5
training_mode: "full"

# or linear only
# learning_rate: 0.0001  # 1e-4
# layer_decay: 0.25  # no effect
# weight_decay: 0.1
# dropout_prob: 0.5
# training_mode: "head_only"


# parameters below here don't change / do much

max_epochs: 5000  
always_train_batchnorm: False
check_val_every_n_epoch: 1
# only does something if cosine_schedule is True
cosine_schedule: False
warmup_epochs: 0
max_cosine_epochs: 100
max_learning_rate_reduction_factor: 0.01