encoder_hub_path: local:/share/nas2/walml/repos/gz-evo/results/baselines/regression/convnextv2_base.fcmae_ft_in22k_in1k_534895718_1753971487/checkpoints/epoch=51-step=26936.ckpt
architecture_name: convnextv2_base.fcmae_ft_in22k_in1k
from_scratch: False
channels: 3  # used for augs
input_size: 224  # used for augs
normalize: False

batch_size: 32  # 32 is good, less than other models
patience: 6
stochastic_depth: 0.4

# deep finetune with decay
learning_rate: 0.0001  # 1e-4   #raised from 1e-5
layer_decay: 0.25
weight_decay: 0.1
dropout_prob: 0.5
training_mode: "full"
scheduler_kwargs: {}

# or linear
# learning_rate: 0.0001  # 1e-4
# layer_decay: 0.25  # no effect
# weight_decay: 0.1
# dropout_prob: 0.5
# training_mode: "head_only"
# scheduler_kwargs: {}

# parameters below here don't change / do much

max_epochs: 5000  
check_val_every_n_epoch: 1
