encoder_hub_path: local:/share/nas2/walml/repos/gz-evo/results/baselines/regression/efficientformerv2_l_534895718_1753972626/checkpoints/epoch=34-step=18130.ckpt
architecture_name: efficientformerv2_l.snap_dist_in1k
from_scratch: False
channels: 3  # used for augs
input_size: 224  # used for augs
normalize: False

batch_size: 128
patience: 6
stochastic_depth: 0.  # has no effect for efficientformer

# deep finetune with decay
learning_rate: 0.00001  # 1e-5, same as other models, late stage training is unstable above this
layer_decay: 0.25
weight_decay: 0.
dropout_prob: 0.
training_mode: "full"

# or linear
# learning_rate: 0.0001  # 1e-4
# layer_decay: 0.25  # no effect
# weight_decay: 0.1
# dropout_prob: 0.5
# training_mode: "head_only"


# parameters below here don't change / do much

max_epochs: 5000  
check_val_every_n_epoch: 1
